### ISSUE TITLE
error while populating

### ISSUE THREAD

**Issue by Dexy2811** [LogicTechCorp/LibraryEx#3]
`[WARNING] [FML]: LibraryEx loaded a new chunk [-151, -122] in dimension -1 (the_nether) while populating chunk [-152, -122], causing cascading worldgen lag.

[WARNING] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config. `

**Comment by LogicTechCorp** [comment]
This is a known issue, but it isn't easy to fix. It is caused by generating structures that are larger than a chunk.
